set_false_path -from [get_ports hps_io_hps_io_sdio_inst_CMD] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_CMD]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D0] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D0]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D1]
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_CLK]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D2] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D2]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D3]
set_false_path -from [get_ports hps_io_hps_io_uart0_inst_RX] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_uart0_inst_TX]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO14] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO14]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO17] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO17]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO19] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO19]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO22] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO22]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO23] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO23]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO25] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO25]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO27] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO27]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO28] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO28]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO29] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO29]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO30] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO30]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO32] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO32]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO33] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO33]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO34] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO34]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO48] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO48]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO53] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO53]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO54] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO54]