// soc_hps_hps_0.v

// This file was auto-generated from altera_hps_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 17.1 590

`timescale 1 ps / 1 ps
module soc_hps_hps_0 #(
		parameter F2S_Width = 0,
		parameter S2F_Width = 0
	) (
		output wire [66:0] h2f_loan_in,               //     h2f_loan_io.in
		input  wire [66:0] h2f_loan_out,              //                .out
		input  wire [66:0] h2f_loan_oe,               //                .oe
		output wire        h2f_rst_n,                 //       h2f_reset.reset_n
		output wire        h2f_user0_clk,             // h2f_user0_clock.clk
		output wire [14:0] mem_a,                     //          memory.mem_a
		output wire [2:0]  mem_ba,                    //                .mem_ba
		output wire        mem_ck,                    //                .mem_ck
		output wire        mem_ck_n,                  //                .mem_ck_n
		output wire        mem_cke,                   //                .mem_cke
		output wire        mem_cs_n,                  //                .mem_cs_n
		output wire        mem_ras_n,                 //                .mem_ras_n
		output wire        mem_cas_n,                 //                .mem_cas_n
		output wire        mem_we_n,                  //                .mem_we_n
		output wire        mem_reset_n,               //                .mem_reset_n
		inout  wire [15:0] mem_dq,                    //                .mem_dq
		inout  wire [1:0]  mem_dqs,                   //                .mem_dqs
		inout  wire [1:0]  mem_dqs_n,                 //                .mem_dqs_n
		output wire        mem_odt,                   //                .mem_odt
		output wire [1:0]  mem_dm,                    //                .mem_dm
		input  wire        oct_rzqin,                 //                .oct_rzqin
		inout  wire        hps_io_sdio_inst_CMD,      //          hps_io.hps_io_sdio_inst_CMD
		inout  wire        hps_io_sdio_inst_D0,       //                .hps_io_sdio_inst_D0
		inout  wire        hps_io_sdio_inst_D1,       //                .hps_io_sdio_inst_D1
		output wire        hps_io_sdio_inst_CLK,      //                .hps_io_sdio_inst_CLK
		inout  wire        hps_io_sdio_inst_D2,       //                .hps_io_sdio_inst_D2
		inout  wire        hps_io_sdio_inst_D3,       //                .hps_io_sdio_inst_D3
		input  wire        hps_io_uart0_inst_RX,      //                .hps_io_uart0_inst_RX
		output wire        hps_io_uart0_inst_TX,      //                .hps_io_uart0_inst_TX
		inout  wire        hps_io_gpio_inst_LOANIO14, //                .hps_io_gpio_inst_LOANIO14
		inout  wire        hps_io_gpio_inst_LOANIO17, //                .hps_io_gpio_inst_LOANIO17
		inout  wire        hps_io_gpio_inst_LOANIO19, //                .hps_io_gpio_inst_LOANIO19
		inout  wire        hps_io_gpio_inst_LOANIO22, //                .hps_io_gpio_inst_LOANIO22
		inout  wire        hps_io_gpio_inst_LOANIO23, //                .hps_io_gpio_inst_LOANIO23
		inout  wire        hps_io_gpio_inst_LOANIO25, //                .hps_io_gpio_inst_LOANIO25
		inout  wire        hps_io_gpio_inst_LOANIO27, //                .hps_io_gpio_inst_LOANIO27
		inout  wire        hps_io_gpio_inst_LOANIO28, //                .hps_io_gpio_inst_LOANIO28
		inout  wire        hps_io_gpio_inst_LOANIO29, //                .hps_io_gpio_inst_LOANIO29
		inout  wire        hps_io_gpio_inst_LOANIO30, //                .hps_io_gpio_inst_LOANIO30
		inout  wire        hps_io_gpio_inst_LOANIO32, //                .hps_io_gpio_inst_LOANIO32
		inout  wire        hps_io_gpio_inst_LOANIO33, //                .hps_io_gpio_inst_LOANIO33
		inout  wire        hps_io_gpio_inst_LOANIO34, //                .hps_io_gpio_inst_LOANIO34
		inout  wire        hps_io_gpio_inst_LOANIO48, //                .hps_io_gpio_inst_LOANIO48
		inout  wire        hps_io_gpio_inst_LOANIO53, //                .hps_io_gpio_inst_LOANIO53
		inout  wire        hps_io_gpio_inst_LOANIO54  //                .hps_io_gpio_inst_LOANIO54
	);

	wire   [8:0] fpga_interfaces_loanio_gpio_loanio2_oe; // fpga_interfaces:loanio_gpio_loanio2_oe -> hps_io:gpio_loanio_loanio2_oe
	wire   [8:0] fpga_interfaces_loanio_gpio_loanio2_o;  // fpga_interfaces:loanio_gpio_loanio2_o -> hps_io:gpio_loanio_loanio2_o
	wire  [28:0] fpga_interfaces_loanio_gpio_loanio1_oe; // fpga_interfaces:loanio_gpio_loanio1_oe -> hps_io:gpio_loanio_loanio1_oe
	wire  [28:0] fpga_interfaces_loanio_gpio_loanio1_o;  // fpga_interfaces:loanio_gpio_loanio1_o -> hps_io:gpio_loanio_loanio1_o
	wire  [28:0] fpga_interfaces_loanio_gpio_loanio0_o;  // fpga_interfaces:loanio_gpio_loanio0_o -> hps_io:gpio_loanio_loanio0_o
	wire  [28:0] hps_io_gpio_loanio_loanio1_i;           // hps_io:gpio_loanio_loanio1_i -> fpga_interfaces:loanio_gpio_loanio1_i
	wire  [28:0] hps_io_gpio_loanio_loanio0_i;           // hps_io:gpio_loanio_loanio0_i -> fpga_interfaces:loanio_gpio_loanio0_i
	wire   [8:0] hps_io_gpio_loanio_loanio2_i;           // hps_io:gpio_loanio_loanio2_i -> fpga_interfaces:loanio_gpio_loanio2_i
	wire  [28:0] fpga_interfaces_loanio_gpio_loanio0_oe; // fpga_interfaces:loanio_gpio_loanio0_oe -> hps_io:gpio_loanio_loanio0_oe

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (F2S_Width != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					f2s_width_check ( .error(1'b1) );
		end
		if (S2F_Width != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					s2f_width_check ( .error(1'b1) );
		end
	endgenerate

	soc_hps_hps_0_fpga_interfaces fpga_interfaces (
		.h2f_loan_in            (h2f_loan_in),                            //     h2f_loan_io.in
		.h2f_loan_out           (h2f_loan_out),                           //                .out
		.h2f_loan_oe            (h2f_loan_oe),                            //                .oe
		.loanio_gpio_loanio0_i  (hps_io_gpio_loanio_loanio0_i),           //     loanio_gpio.loanio0_i
		.loanio_gpio_loanio0_oe (fpga_interfaces_loanio_gpio_loanio0_oe), //                .loanio0_oe
		.loanio_gpio_loanio0_o  (fpga_interfaces_loanio_gpio_loanio0_o),  //                .loanio0_o
		.loanio_gpio_loanio1_i  (hps_io_gpio_loanio_loanio1_i),           //                .loanio1_i
		.loanio_gpio_loanio1_oe (fpga_interfaces_loanio_gpio_loanio1_oe), //                .loanio1_oe
		.loanio_gpio_loanio1_o  (fpga_interfaces_loanio_gpio_loanio1_o),  //                .loanio1_o
		.loanio_gpio_loanio2_i  (hps_io_gpio_loanio_loanio2_i),           //                .loanio2_i
		.loanio_gpio_loanio2_oe (fpga_interfaces_loanio_gpio_loanio2_oe), //                .loanio2_oe
		.loanio_gpio_loanio2_o  (fpga_interfaces_loanio_gpio_loanio2_o),  //                .loanio2_o
		.h2f_rst_n              (h2f_rst_n),                              //       h2f_reset.reset_n
		.h2f_user0_clk          (h2f_user0_clk)                           // h2f_user0_clock.clk
	);

	soc_hps_hps_0_hps_io hps_io (
		.gpio_loanio_loanio0_i     (hps_io_gpio_loanio_loanio0_i),           // gpio_loanio.loanio0_i
		.gpio_loanio_loanio0_oe    (fpga_interfaces_loanio_gpio_loanio0_oe), //            .loanio0_oe
		.gpio_loanio_loanio0_o     (fpga_interfaces_loanio_gpio_loanio0_o),  //            .loanio0_o
		.gpio_loanio_loanio1_i     (hps_io_gpio_loanio_loanio1_i),           //            .loanio1_i
		.gpio_loanio_loanio1_oe    (fpga_interfaces_loanio_gpio_loanio1_oe), //            .loanio1_oe
		.gpio_loanio_loanio1_o     (fpga_interfaces_loanio_gpio_loanio1_o),  //            .loanio1_o
		.gpio_loanio_loanio2_i     (hps_io_gpio_loanio_loanio2_i),           //            .loanio2_i
		.gpio_loanio_loanio2_oe    (fpga_interfaces_loanio_gpio_loanio2_oe), //            .loanio2_oe
		.gpio_loanio_loanio2_o     (fpga_interfaces_loanio_gpio_loanio2_o),  //            .loanio2_o
		.mem_a                     (mem_a),                                  //      memory.mem_a
		.mem_ba                    (mem_ba),                                 //            .mem_ba
		.mem_ck                    (mem_ck),                                 //            .mem_ck
		.mem_ck_n                  (mem_ck_n),                               //            .mem_ck_n
		.mem_cke                   (mem_cke),                                //            .mem_cke
		.mem_cs_n                  (mem_cs_n),                               //            .mem_cs_n
		.mem_ras_n                 (mem_ras_n),                              //            .mem_ras_n
		.mem_cas_n                 (mem_cas_n),                              //            .mem_cas_n
		.mem_we_n                  (mem_we_n),                               //            .mem_we_n
		.mem_reset_n               (mem_reset_n),                            //            .mem_reset_n
		.mem_dq                    (mem_dq),                                 //            .mem_dq
		.mem_dqs                   (mem_dqs),                                //            .mem_dqs
		.mem_dqs_n                 (mem_dqs_n),                              //            .mem_dqs_n
		.mem_odt                   (mem_odt),                                //            .mem_odt
		.mem_dm                    (mem_dm),                                 //            .mem_dm
		.oct_rzqin                 (oct_rzqin),                              //            .oct_rzqin
		.hps_io_sdio_inst_CMD      (hps_io_sdio_inst_CMD),                   //      hps_io.hps_io_sdio_inst_CMD
		.hps_io_sdio_inst_D0       (hps_io_sdio_inst_D0),                    //            .hps_io_sdio_inst_D0
		.hps_io_sdio_inst_D1       (hps_io_sdio_inst_D1),                    //            .hps_io_sdio_inst_D1
		.hps_io_sdio_inst_CLK      (hps_io_sdio_inst_CLK),                   //            .hps_io_sdio_inst_CLK
		.hps_io_sdio_inst_D2       (hps_io_sdio_inst_D2),                    //            .hps_io_sdio_inst_D2
		.hps_io_sdio_inst_D3       (hps_io_sdio_inst_D3),                    //            .hps_io_sdio_inst_D3
		.hps_io_uart0_inst_RX      (hps_io_uart0_inst_RX),                   //            .hps_io_uart0_inst_RX
		.hps_io_uart0_inst_TX      (hps_io_uart0_inst_TX),                   //            .hps_io_uart0_inst_TX
		.hps_io_gpio_inst_LOANIO14 (hps_io_gpio_inst_LOANIO14),              //            .hps_io_gpio_inst_LOANIO14
		.hps_io_gpio_inst_LOANIO17 (hps_io_gpio_inst_LOANIO17),              //            .hps_io_gpio_inst_LOANIO17
		.hps_io_gpio_inst_LOANIO19 (hps_io_gpio_inst_LOANIO19),              //            .hps_io_gpio_inst_LOANIO19
		.hps_io_gpio_inst_LOANIO22 (hps_io_gpio_inst_LOANIO22),              //            .hps_io_gpio_inst_LOANIO22
		.hps_io_gpio_inst_LOANIO23 (hps_io_gpio_inst_LOANIO23),              //            .hps_io_gpio_inst_LOANIO23
		.hps_io_gpio_inst_LOANIO25 (hps_io_gpio_inst_LOANIO25),              //            .hps_io_gpio_inst_LOANIO25
		.hps_io_gpio_inst_LOANIO27 (hps_io_gpio_inst_LOANIO27),              //            .hps_io_gpio_inst_LOANIO27
		.hps_io_gpio_inst_LOANIO28 (hps_io_gpio_inst_LOANIO28),              //            .hps_io_gpio_inst_LOANIO28
		.hps_io_gpio_inst_LOANIO29 (hps_io_gpio_inst_LOANIO29),              //            .hps_io_gpio_inst_LOANIO29
		.hps_io_gpio_inst_LOANIO30 (hps_io_gpio_inst_LOANIO30),              //            .hps_io_gpio_inst_LOANIO30
		.hps_io_gpio_inst_LOANIO32 (hps_io_gpio_inst_LOANIO32),              //            .hps_io_gpio_inst_LOANIO32
		.hps_io_gpio_inst_LOANIO33 (hps_io_gpio_inst_LOANIO33),              //            .hps_io_gpio_inst_LOANIO33
		.hps_io_gpio_inst_LOANIO34 (hps_io_gpio_inst_LOANIO34),              //            .hps_io_gpio_inst_LOANIO34
		.hps_io_gpio_inst_LOANIO48 (hps_io_gpio_inst_LOANIO48),              //            .hps_io_gpio_inst_LOANIO48
		.hps_io_gpio_inst_LOANIO53 (hps_io_gpio_inst_LOANIO53),              //            .hps_io_gpio_inst_LOANIO53
		.hps_io_gpio_inst_LOANIO54 (hps_io_gpio_inst_LOANIO54)               //            .hps_io_gpio_inst_LOANIO54
	);

endmodule
